# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=20),
        ),
    ]
